command:
  - streamlit
  - run
  - app.py

env:
  # Unity Catalog Configuration
  - name: CATALOG
    value: "payments_lakehouse"
  - name: SCHEMA_BRONZE
    value: "bronze"
  - name: SCHEMA_SILVER
    value: "silver"
  - name: SCHEMA_GOLD
    value: "gold"
  
  # Application Settings
  - name: APP_NAME
    value: "Payment Authorization Premium"
  - name: APP_VERSION
    value: "3.0.0-premium"
  - name: APP_TYPE
    value: "premium"
  - name: LOG_LEVEL
    value: "INFO"
  
  # Feature Flags
  - name: ENABLE_GENIE
    value: "true"
  - name: ENABLE_SMART_CHECKOUT
    value: "true"
  - name: ENABLE_SMART_RETRY
    value: "true"
  - name: ENABLE_REASON_CODE_ANALYTICS
    value: "true"
  - name: ENABLE_MULTI_PAGE
    value: "true"
  - name: ENABLE_ADVANCED_VISUALIZATIONS
    value: "true"
  - name: ENABLE_GEO_ANALYTICS
    value: "true"
  - name: ENABLE_PYDECK_MAPS
    value: "true"
  - name: ENABLE_CHOROPLETH_MAPS
    value: "true"
  - name: ENABLE_COUNTRY_DRILLDOWN
    value: "true"
  - name: ENABLE_PREMIUM_UI
    value: "true"
  
  # Data Refresh Settings
  - name: DATA_REFRESH_INTERVAL
    value: "30"
  - name: CACHE_TTL
    value: "60"
  - name: CACHE_TTL_LONG
    value: "300"
