# ============================================================================
# Databricks App Configuration
# Payment Authorization Premium App - Enterprise Edition
# ============================================================================
# Version: 3.0.0 (Premium)
# Last Updated: 2026-01-31
# Purpose: Enterprise-grade app with advanced geo-analytics and premium UI/UX
# ============================================================================

command:
  - streamlit
  - run
  - app.py
  - --server.port=8501
  - --server.address=0.0.0.0
  - --server.headless=true
  - --server.enableCORS=false
  - --server.enableXsrfProtection=false
  - --browser.gatherUsageStats=false
  - --server.fileWatcherType=none
  - --server.maxUploadSize=200
  - --server.maxMessageSize=200
  - --server.enableWebsocketCompression=false

env:
  # Streamlit Configuration
  - name: 'STREAMLIT_GATHER_USAGE_STATS'
    value: 'false'
  - name: 'STREAMLIT_BROWSER_GATHER_USAGE_STATS'
    value: 'false'
  - name: 'STREAMLIT_SERVER_HEADLESS'
    value: 'true'
  - name: 'STREAMLIT_SERVER_PORT'
    value: '8501'
  - name: 'STREAMLIT_SERVER_ENABLE_CORS'
    value: 'false'
  - name: 'STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION'
    value: 'false'
  
  # Unity Catalog Configuration
  - name: 'CATALOG'
    value: 'payments_lakehouse'
  - name: 'SCHEMA_BRONZE'
    value: 'bronze'
  - name: 'SCHEMA_SILVER'
    value: 'silver'
  - name: 'SCHEMA_GOLD'
    value: 'gold'
  
  # Application Settings
  - name: 'APP_NAME'
    value: 'Payment Authorization Premium'
  - name: 'APP_VERSION'
    value: '3.0.0-premium'
  - name: 'APP_TYPE'
    value: 'premium'
  - name: 'LOG_LEVEL'
    value: 'INFO'
  
  # Feature Flags (Premium - All Features Enabled)
  - name: 'ENABLE_GENIE'
    value: 'true'
  - name: 'ENABLE_SMART_CHECKOUT'
    value: 'true'
  - name: 'ENABLE_SMART_RETRY'
    value: 'true'
  - name: 'ENABLE_REASON_CODE_ANALYTICS'
    value: 'true'
  - name: 'ENABLE_MULTI_PAGE'
    value: 'true'
  - name: 'ENABLE_ADVANCED_VISUALIZATIONS'
    value: 'true'
  - name: 'ENABLE_GEO_ANALYTICS'
    value: 'true'
  - name: 'ENABLE_PYDECK_MAPS'
    value: 'true'
  - name: 'ENABLE_CHOROPLETH_MAPS'
    value: 'true'
  - name: 'ENABLE_COUNTRY_DRILLDOWN'
    value: 'true'
  - name: 'ENABLE_PREMIUM_UI'
    value: 'true'
  
  # Data Refresh Settings (Real-time)
  - name: 'DATA_REFRESH_INTERVAL'
    value: '30'  # 30 seconds for real-time updates
  - name: 'CACHE_TTL'
    value: '60'  # 1 minute cache for real-time feel
  - name: 'CACHE_TTL_LONG'
    value: '300'  # 5 minutes for heavy queries
  
  # Databricks Connection
  - name: 'DATABRICKS_HOST'
    value: 'auto'
  - name: 'DATABRICKS_TOKEN'
    value: 'auto'
  
  # Premium Features
  - name: 'ENABLE_ANIMATIONS'
    value: 'true'
  - name: 'ENABLE_GLASSMORPHISM'
    value: 'true'
  - name: 'ENABLE_GRADIENTS'
    value: 'true'

# Resource Allocation - Optimized for stability
# Note: Reduced from 16Gi/8CPU to prevent resource unavailability issues
resources:
  limits:
    memory: "8Gi"       # Sufficient for Streamlit + PyDeck + Plotly
    cpu: "4"            # Enough for visualization rendering
  requests:
    memory: "4Gi"       # Initial memory reservation
    cpu: "2"            # Initial CPU cores

# Health Check Configuration - EXTREMELY tolerant to prevent 502 errors
healthCheck:
  path: "/_stcore/health"
  port: 8501
  initialDelaySeconds: 300   # 5 minutes - VERY generous for slow starts
  periodSeconds: 60          # Check every 60 seconds (very patient)
  timeoutSeconds: 30         # 30 second timeout (allow slow responses)
  successThreshold: 1
  failureThreshold: 20       # VERY tolerant - 20 failures before restart (20 minutes)

# Application Metadata
metadata:
  name: "pagonxt-getnet-rates"
  displayName: "PagoNxt Getnet - Payment Authorization Platform"
  description: |
    PagoNxt Getnet payment authorization analytics platform with advanced geo-analytics.
    
    Premium Features:
    - Executive Dashboard: Premium KPI cards with PagoNxt Getnet brand colors
    - Global Geo-Analytics: Interactive 3D bubble maps (PyDeck) and choropleth maps
    - Country Drill-Down: Detailed analysis for 18+ countries with lat/lon mapping
    - Smart Checkout: Advanced solution optimization with cascading logic
    - Decline Analysis: Deep-dive reason code analytics with heat maps
    - Smart Retry: ML-powered retry recommendations with ROI calculator
    - Performance Metrics: Comprehensive analytics with time-series analysis
    - Genie AI Assistant: Natural language query interface
    - Settings & Config: Policy management and customization
    
    PagoNxt Getnet Branded UI/UX:
    - Purple/Blue gradient theme (#5B2C91 → #00A3E0)
    - Modern fintech design with premium styling
    - 500+ lines of custom CSS
    - Smooth animations and transitions
    - Glass-morphism effects
    - Gradient headers and cards
    - Responsive design for all devices
    
    Perfect for: Executive presentations, production use, enterprise deployments
    
    Built with: Streamlit, Plotly, PyDeck, PySpark, Delta Lake, MLflow, Databricks SQL
  version: "3.0.0-pagonxt"
  author: "PagoNxt Getnet + Databricks"
  license: "Databricks License"
  homepage: "https://github.com/databricks/payment-authorization-demo"
  
  tags:
    - "payments"
    - "fintech"
    - "analytics"
    - "databricks"
    - "lakehouse"
    - "streamlit"
    - "machine-learning"
    - "real-time"
    - "geo-analytics"
    - "premium"
    - "enterprise"
    - "pydeck"
    - "choropleth"
    - "multi-page"
    - "advanced-visualizations"
  
  categories:
    - "Financial Services"
    - "Analytics & BI"
    - "Machine Learning"
    - "Enterprise Solutions"
  
  keywords:
    - "payment authorization"
    - "approval rate optimization"
    - "smart checkout"
    - "decline analysis"
    - "smart retry"
    - "geo-analytics"
    - "geographic visualization"
    - "country drill-down"
    - "premium dashboard"
    - "enterprise analytics"
