# Databricks App Configuration
# Payment Authorization Command Center

# Command to run the Streamlit app
# Path must be relative to the app directory (app.py in the same folder as app.yaml)
command: ['streamlit', 'run', 'app.py', '--server.port=8501', '--server.address=0.0.0.0']

# Environment variables
env:
  - name: 'STREAMLIT_GATHER_USAGE_STATS'
    value: 'false'
  - name: 'STREAMLIT_BROWSER_GATHER_USAGE_STATS'
    value: 'false'
  - name: 'STREAMLIT_SERVER_HEADLESS'
    value: 'true'
  - name: 'CATALOG'
    value: 'payments_lakehouse'
  - name: 'SCHEMA_BRONZE'
    value: 'bronze'
  - name: 'SCHEMA_SILVER'
    value: 'silver'
  - name: 'SCHEMA_GOLD'
    value: 'gold'

# Resource limits (optional)
# Uncomment and adjust as needed
# resources:
#   limits:
#     memory: "4Gi"
#     cpu: "2"
#   requests:
#     memory: "2Gi"
#     cpu: "1"

# Health check configuration (optional)
# healthCheck:
#   path: "/_stcore/health"
#   port: 8501
#   initialDelaySeconds: 30
#   periodSeconds: 10

# App metadata
metadata:
  name: "payment-authorization-command-center"
  description: "Real-time payment authorization analytics with Smart Checkout, Decline Analysis, and Smart Retry recommendations"
  version: "1.0.0"
  tags:
    - "payments"
    - "analytics"
    - "databricks"
    - "lakehouse"
    - "streamlit"
